spring:
  datasource:
    url: jdbc:postgresql://db.wwvukvluhumqvwqswdft.supabase.co:5432/postgres
    username: postgres
    password: MNDyvrjjPlCuv6Ci
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
